# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = swaybg -o \* -i /usr/share/wallpapers/cachyos-wallpapers/Metal.png -m fill
exec-once = waybar &
exec-once = fcitx5 -d &
exec-once = mako &
exec-once = nm-applet --indicator &
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown" &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# my autostarts

exec-once = librewolf &
exec-once = flatpak run org.ferdium.Ferdium &
exec-once = flatpak run org.signal.Signal &
exec-once = thunderbird &
exec-once = flatpak run dev.pulsar_edit.Pulsar &
exec-once = flatpak run com.logseq.Logseq &
exec-once = flatpak run com.spotify.Client &
exec-once = flatpak run com.bitwarden.desktop

exec-once = wl-paste --type text --watch cliphist store # Stores only text
exec-once = wl-paste --type image --watch cliphist store # Stores only images

# Assign to workspaces

windowrule = workspace 1, match:class (librewolf)
windowrule = workspace 2, match:class (Ferdium)
windowrule = workspace 2, match:class (signal)
windowrule = workspace 3, match:class (org.mozilla.Thunderbird)
windowrule = workspace 4, match:class (Pulsar)
windowrule = workspace 7, match:class (Logseq)
windowrule = workspace 8, match:class (Spotify)
windowrule = workspace 10, match:class (Bitwarden)

# ## Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &

# ## Idle configuration
exec-once = $idlehandler
